version: "3"

services:
  assistant_api:
    build:
      context: ./api
    env_file:
      - .env
    ports:
      - "8000:8000"

  assistant_frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - assistant_api
    ports:
      - "8501:8501"
