services:
  # Github PM Assistant web service
  - type: web
    name: github-pm-assistant
    runtime: python
    branch: chore/add-render-deployment
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: api
    buildFilter:
      paths:
        - api/**
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_PERSONAL_ACCESS_TOKEN
        sync: false
      - key: GITHUB_REPOSITORY
        sync: false
